# In this notebook, we'are going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically , we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating  tensors
* Tensors & Numpy
* Using @tf.fuction(a way to speed up our regular Python functions)
* Using GPUs with TensorFlow( or TPUs)
* Exercises to try for yourself



# Introduct to Tensors

In [1]:
 # Import Tensorflow
 import tensorflow as tf 
 print(tf.__version__)

2.6.0


In [2]:
 # Create Tensors wit tf.constant()

 scalar = tf.constant(7)
 scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
 # Check the number of dimensions of a tensor (ndim stands for number of dimensions)
 scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
#Check the dimension of our vector
vector.ndim

1

In [6]:
# create a matrix (has more than 1 Dimension )
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8.,9.]],
                              dtype=tf.float16 # Specifying the data type
                             )
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
# what's the number dimensions of the other another_matrix?
another_matrix.ndim

2

In [10]:
# let create a tensor
tensor = tf.constant([[
                      [1,2,3],[4,5,6]],
                      [[7,8,9],[10,11,12,]],
                      [[13,14,15], [16,17,18]]
                      ])
tensor 

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

what we've created so far
* Scalar : a single number
* Vector : a numbe with direction (e.g. wind speed and direction
* Matrix : a 2-dimensional array of numbers
* Tensor: and n-dimensional array of numbers ( when n can be any number , a 0-dimensionl tensor is a scalar, a 1-dimensional tensor is a vector )

### Creating Tensors wit tf.Variable

In [12]:
#create the tensor wit tf.variable () as above
changeable_tensor = tf.Variable([10,7])
unChangeable_tensor = tf.constant([10,7])
changeable_tensor, unChangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# Let's try change one of the elements in our changeable tensor ((Intentionnal Error))
# changeable_tensor[0] = 7
# changeable_tensor

In [14]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
# Let's try change on our unchangeable tensor ((Intentionnal Error))
# unChangeable_tensor[0].assign(7)
# unChangeable_tensor

### Creating random tensors
Random tensors of some abitrary size wihich contain random numbers


In [16]:
# Create two random ( but the same ) tensors
random_1 = tf.random.Generator.from_seed(33) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(33)
random_2 = random_2.normal(shape=(3,2))

# Are they equal ?
random_1,random_2 , random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.1589871 ,  1.302304  ],
        [ 0.9592239 ,  0.85874265],
        [-1.5181769 ,  1.4020647 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.1589871 ,  1.302304  ],
        [ 0.9592239 ,  0.85874265],
        [-1.5181769 ,  1.4020647 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

###  Shuffle the order of elements in a tensor

In [17]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't affect the learning )
not_shuffled = tf.constant([
                         [10,7],
                         [3,4],
                         [2,5]
])
not_shuffled.ndim
not_shuffled


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [18]:
# Shuffle our non-shuffled tensor
 
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

✨⚙ TensorFlow documentation on Random seed Generation
https://www.tensorflow.org/api_docs/python/tf/random/set_seed

It will keep our shuffled tensor to be in the same order, we've got to use the global level random seed as well as the operation  level random seed:

> Rule 4 : "If both the global and the operation seed are set : Both seeds are used in conjuction to determine the random sequence."

In [19]:
# Shuffle again with seed our non-shuffled tensor
tf.random.set_seed(42)  # global level seed
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### Other ways to make tensor

In [20]:
#creating tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [21]:
 # Create a tensor of all zeroes
 tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensors
The main difference between Numpy arrays and TensorFlow tensors is that tensors can be run on a GPU computing )

In [22]:
 # We can also turn Numpy arrays into tensors
 import numpy as np 
numpy_A = np.arange(1,25, dtype=np.int32) #create a Numpy array between 1 and 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [23]:
A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [24]:
A.ndim

3

### Getting inform tensors

When dealing with tensors we probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or dimension
* Size

In [25]:
# Create a rank 4 tensor ( 4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [26]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [27]:
rank_4_tensor.shape, rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [28]:
# Get various attributes of our tensor
print("DataType of evry elements:" , rank_4_tensor.dtype)
print("Number of dimensions (rank) : ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ",rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor))
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor).numpy())

DataType of evry elements: <dtype: 'float32'>
Number of dimensions (rank) :  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor:  120


### Indexing Tensors
Tensors can be indexed just like Python lists.

In [29]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [30]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [31]:
rank_4_tensor[:1, :, :,:1]

<tf.Tensor: shape=(1, 3, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [32]:
 # Create a rank 2 tensor ( 2 dimensions)
 rank_2_tensor = tf.constant ([[10,7], [2,4]])
 rank_2_tensor.shape, rank_2_tensor.ndim
 

(TensorShape([2, 2]), 2)

In [33]:
# Get the last item of each row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [34]:
# Adding extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 4]]], dtype=int32)>

In [35]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" mean expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 4]]], dtype=int32)>

In [36]:
tf.expand_dims(rank_2_tensor, axis=0)  

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 2,  4]]], dtype=int32)>

### Manipulating tensors(tensor operations)
**Basic operations**


In [37]:
# We can add values to a tensor using the addition operator
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [38]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [39]:
# Multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [40]:
# Substraction
tensor -10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [41]:
# We can use the tensorflow built-in function 
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

### Matrix Multiplicaion
In machine  learning , matrix multiplications is one of the common operation

📖 *** Resource: *** Info and example of matrix multiplications : https://mathsisfun.com/algebra/matrix-multiplying.html

There are two rules our tensors (or matrices) need to fulfil if we're going to matrix multiply them :
1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions

In [42]:
 # Matrix  multiplication

In [43]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [44]:
tensor, tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>)

In [45]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [46]:
# Matrix multiplication with python operation "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [47]:
tensor.shape

TensorShape([2, 2])

In [48]:
# Create a tensor of (3,2) tensor
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

# Create another (3,2) tensor
Y = tf.constant([[7,8] , [9,10], [11,12]])

In [49]:
X , Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [50]:
# Try to matrix multiply tensors of same shape (Intentional Error)
# tf.matmul(X,Y)

In [51]:
# Try to matrix multiply tensors of same shape ( Let's change the Shape of Y)
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [52]:
X.shape, tf.reshape(Y,shape=(2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [53]:
# Try to matrix mulitply X by reshaped Y
X @ tf.reshape(Y, shape=(2,3))
 

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [54]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [55]:
tf.reshape(X,shape=(2,3)).shape, Y.shape


(TensorShape([2, 3]), TensorShape([3, 2]))

In [56]:
# Try to reshape X , instead of Y
tf.matmul(tf.reshape(X, shape=(2,3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [57]:
 # Can do the same with transpose
X,tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [58]:
 # Try matrix multiplication with transpose rather than reshape
 tf.matmul (tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [59]:
X, Y


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

**The dot product**
Matrix multiplication is also referred to as the dot product
We can perform matrix multiplication using :
* `tf.matmul()`
* `tf.tensordot()`
* `@`

In [60]:
# Perform the dot product on X and Y ( requires X or Y to be transposed)
tf.tensordot(tf.transpose(X),Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [61]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [62]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [63]:
# Check the values of Y , reshape Y and transposed Y
print("Normal Y:")
print (Y,"\n")

print("Y reshaped to (2,3):")
print(tf.reshape(Y,(2,3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))



Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Generally, when performing matrix multiplication on tow tensors and of the axes doesn't line up, we will transpose (rather than reshape) one of the tensors to get satisfy the matrix multiplication rules

### Changing the datatype of a tensor

In [64]:
# Create a new tensor with default datatype (float 32)
B = tf.constant([1.2,3.4])
B.dtype

tf.float32

In [65]:
C = tf.constant([2,4])
C.dtype

tf.int32

In [66]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B,dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.2, 3.4], dtype=float16)>,
 tf.float16)

In [67]:
# Change from int32 TO Float32
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 4.], dtype=float32)>

In [68]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([2., 4.], dtype=float16)>

### Aggregating tensors
Aggregating tensors = condensing them from mulitple values down to a smaller amount values.

In [71]:
# Getting the absolute values
D = tf.constant([-8, -23])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -8, -23], dtype=int32)>

In [72]:
# Getting the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 8, 23], dtype=int32)>

Let's go through the following forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [74]:
# Create a random tensor of with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0,100, size=50))

In [83]:
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([22, 38, 93, 80, 77, 10, 58, 61, 87, 91, 93, 63, 32, 28, 55, 66, 24,
       73, 54, 48,  9, 44,  2, 14,  6,  7, 36, 80, 35, 65, 27, 60, 57, 24,
       23, 83, 41,  2,  9, 66, 95, 38, 48, 68, 76, 18,  0, 14, 32, 28])>

In [75]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [77]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [78]:
# Finde the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=95>

In [79]:
# Find the Mean 
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=45>

In [80]:
# Find the Sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2260>

🔬🧪 ***Exercise*** let Find the variance and standard deviation of our `E`  tensor using Tensorflow methods.

In [82]:
# Find the variance of our tensor ( first acess tensorflow_probability)

import tensorflow_probability as tfp 
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=787>

In [88]:
# Finde the variance of our E tensor method 2
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=787.2799>

In [84]:
# Find the standard deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.058508>

In [85]:
tf.cast(E, dtype=tf.float32)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([22., 38., 93., 80., 77., 10., 58., 61., 87., 91., 93., 63., 32.,
       28., 55., 66., 24., 73., 54., 48.,  9., 44.,  2., 14.,  6.,  7.,
       36., 80., 35., 65., 27., 60., 57., 24., 23., 83., 41.,  2.,  9.,
       66., 95., 38., 48., 68., 76., 18.,  0., 14., 32., 28.],
      dtype=float32)>

### Let find the positional maximum and minium 

In [90]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [94]:
# Find the positional maximum
tf.argmax(F)


<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [99]:
# Index on our largest value postion
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [96]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [101]:
# Check for equality
# assert F[tf.argmax(F)] == tf.reduce_max(F)
F[tf.argmax(F)] == tf.reduce_max(F)


<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [102]:
# Find the position minum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [105]:
# Find the minium using the postional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

#### Squeezing a tensor(removing all single dimensions)

In [111]:
# Create a tensor to get started
tf.random.set_seed(42)
G= tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [108]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [109]:
G_sqeezed = tf.squeeze(G)
G_sqeezed, G_sqeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

#### One-Hot Encode 

In [114]:
# Create a list of indices
some_list =[0,1,2,3]  # Could be red, green , blue purple


# One hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [115]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="Yoh I like deep learning" , off_value="I also like football")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yoh I like deep learning', b'I also like football',
        b'I also like football', b'I also like football'],
       [b'I also like football', b'Yoh I like deep learning',
        b'I also like football', b'I also like football'],
       [b'I also like football', b'I also like football',
        b'Yoh I like deep learning', b'I also like football'],
       [b'I also like football', b'I also like football',
        b'I also like football', b'Yoh I like deep learning']],
      dtype=object)>

### Squaring, log, square root

In [116]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [117]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [119]:
# Find the square root
tf.math.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [121]:
# Find the log
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

Tensorflow interacts beautifully with NumPy arrays

In [123]:
# Create a tensor directly from a Numpy array
J = tf.constant(np.array([3.,5.,2.]))
J


<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 5., 2.])>

In [124]:
# Convert Our tensor back to a Numpy array
np.array(J), type(np.array(J))

(array([3., 5., 2.]), numpy.ndarray)

In [125]:
# Convert tensor J to a Numpy array
J.numpy() , type(J.numpy())

(array([3., 5., 2.]), numpy.ndarray)

In [126]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3.,4.,5.]))
tensor_J = tf.constant([2.,3.,1.])

#Check the datatypes of each
numpy_J.dtype, tensor_J.dtype 

(tf.float64, tf.float32)

### Finding access to GPU

In [3]:
import tensorflow as tf 
# tf.config.list_physical_devices()
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [4]:
!nvidia-smi


Wed Sep 29 04:35:35 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.63.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8    29W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

🎊 ***Note:***  If we have access to a CUDA-enabled GPU, Tensorflow will automatically use it whenever possible